FROM hasura/graphql-engine:v2.44.0

# Copy Hasura metadata to the container
COPY hasura/metadata /hasura-metadata

# Note: No migrations directory exists yet, so we don't copy it
# When migrations are added later, uncomment the line below:
# COPY hasura/migrations /hasura-migrations

# The container will use environment variables for configuration
# Hasura will automatically read metadata from /hasura-metadata