services:
  - type: web
    name: web
    project: pegasus
    environment: Prod
    env: node
    region: ohio
    plan: pro
    rootDir: .
    buildFilter:
      paths:
        - "apps/web/**"
        - "packages/**"
        - "turbo.json"
        - "pnpm*"
    buildCommand: |
      corepack enable
      pnpm install --no-frozen-lockfile
      cd packages/api-types && pnpm build
      cd ../../apps/web && pnpm build
    startCommand: cd apps/web && PORT=10000 pnpm start
    healthCheckPath: /api/health
    port: 10000
    # Optionally add repo/branch/autodeploy here
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://api-82a7.onrender.com/api
      - key: NODE_ENV
        value: production
      - key: TURBO_REMOTE_ONLY
        value: "true"
      - key: TURBO_TEAM
        value: "your-team-name"
      - key: TURBO_TOKEN
        sync: false
      - key: PNPM_VERSION
        value: "9.0.0"
      - key: PORT
        value: "10000"

  - type: web
    name: api
    project: pegasus
    environment: Prod
    env: node
    region: ohio
    plan: pro
    rootDir: .
    buildFilter:
      paths:
        - "apps/api/**"
        - "packages/**"
        - "turbo.json"
        - "pnpm*"
    buildCommand: |
      export NODE_ENV=production
      corepack enable
      pnpm install --no-frozen-lockfile
      cd packages/api-types && pnpm build
      cd ../../apps/api && pnpm build
    startCommand: cd apps/api && PORT=4000 pnpm start:prod
    healthCheckPath: /api/health
    port: 4000
    # Optionally add repo/branch/autodeploy here
    envVars:
      - key: NODE_ENV
        value: production
      - key: WEB_URL
        fromService:
          type: web
          name: web
          property: url
      - key: TURBO_REMOTE_ONLY
        value: "true"
      - key: TURBO_TEAM
        value: "your-team-name"
      - key: TURBO_TOKEN
        sync: false
      - key: PNPM_VERSION
        value: "9.0.0"
      - key: PORT
        value: "4000"
      - key: DATABASE_URL
        value: postgresql://pegasus_v8q7_user:AVfv6bTVCiQ1Cjj5PieSgEB7kUwwc173@dpg-d0pq558dl3ps73b1oshg-a/pegasus_v8q7

databases:
  - name: pegasus-prod
    project: pegasus
    environment: Prod
    plan: pro
    region: ohio
    ipAllowList: [] # Only allow internal connections
