services:
  - type: web
    name: web
    env: node
    root: apps/web
    buildFilter:
      paths:
        - apps/web/**
        - packages/**
        - turbo.json
        - pnpm-lock.yaml
        - pnpm-workspace.yaml
    build:
      command: |
        corepack enable
        pnpm install --frozen-lockfile
        pnpm turbo run build --filter=web
    start: pnpm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://api.onrender.com/api
      - key: NODE_ENV
        value: production
      - key: TURBO_REMOTE_ONLY
        value: "true"
      - key: TURBO_TEAM
        value: "your-team-name"
      - key: TURBO_TOKEN
        sync: false
      - key: PNPM_VERSION
        value: "8.6.0"
    autoDeploy: true
    caching:
      paths:
        - ../../node_modules
        - .next/cache

  - type: web
    name: api
    env: node
    root: apps/api
    buildFilter:
      paths:
        - apps/api/**
        - packages/**
        - turbo.json
        - pnpm-lock.yaml
        - pnpm-workspace.yaml
    build:
      command: |
        corepack enable
        pnpm install --frozen-lockfile
        pnpm turbo run build --filter=api
    start: pnpm start:prod
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString
      - key: PORT
        value: 4000
      - key: NODE_ENV
        value: production
      - key: TURBO_REMOTE_ONLY
        value: "true"
      - key: TURBO_TEAM
        value: "your-team-name"
      - key: TURBO_TOKEN
        sync: false
      - key: PNPM_VERSION
        value: "8.6.0"
    healthCheckPath: /api/health
    autoDeploy: true
    addons:
      - type: postgresql
        name: postgres-db
        plan: free
        ipAllowList: []


# Uncomment below to add Redis
# - type: redis
#   name: app-redis
#   ipAllowList: []  # Only allow internal connections
#   plan: free