# render.yaml
services:
  - type: web
    name: web
    env: node
    region: ohio
    plan: free
    rootDir: apps/web
    buildFilter:
      paths:
        - "apps/web/**"
        - "packages/**"
        - "turbo.json"
        - "pnpm*"
    buildCommand: |
        corepack enable
        pnpm install --frozen-lockfile
        pnpm turbo run build --filter=web
    startCommand: pnpm start
    healthCheckPath: /api/health
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: ${services.api.url}/api
      - key: NODE_ENV
        value: production
      - key: TURBO_REMOTE_ONLY
        value: "true"
      - key: TURBO_TEAM
        value: "your-team-name"
      - key: TURBO_TOKEN
        sync: false
      - key: PNPM_VERSION
        value: "8.6.0"

  - type: web
    name: api
    env: node
    region: ohio
    plan: free
    rootDir: apps/api
    buildFilter:
      paths:
        - "apps/api/**"
        - "packages/**"
        - "turbo.json"
        - "pnpm*"
    buildCommand: |
        corepack enable
        pnpm install --frozen-lockfile
        pnpm turbo run build --filter=api
    startCommand: pnpm start:prod
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: TURBO_REMOTE_ONLY
        value: "true"
      - key: TURBO_TEAM
        value: "your-team-name"
      - key: TURBO_TOKEN
        sync: false
      - key: PNPM_VERSION
        value: "8.6.0"

# Uncomment below to add Redis
# - type: redis
#   name: app-redis
#   ipAllowList: []  # Only allow internal connections
#   plan: free