# render.yaml
services:
  - type: web
    name: web
    env: node
    region: ohio
    plan: free
    rootDir: .
    buildFilter:
      paths:
        - "apps/web/**"
        - "packages/**"
        - "turbo.json"
        - "pnpm*"
    buildCommand: |
        export NODE_ENV=production
        export NEXT_PUBLIC_API_URL="https://api-nrnt.onrender.com/api"
        # Validate the API URL has been properly set
        echo "Validating API URL: $NEXT_PUBLIC_API_URL"
        if [[ "$NEXT_PUBLIC_API_URL" == *"$"* ]]; then
          echo "ERROR: Variable contains unprocessed template"
          exit 1
        fi
        corepack enable
        # Install all dependencies including dev dependencies
        NODE_ENV=development pnpm install --no-frozen-lockfile
        # Build API types first
        cd packages/api-types && pnpm build
        # Build web app
        cd ../../apps/web && pnpm build
    startCommand: cd apps/web && PORT=10000 pnpm start
    healthCheckPath: /api/health
    port: 10000
    envVars:
      - key: NODE_ENV
        value: production
      - key: TURBO_REMOTE_ONLY
        value: "true"
      - key: TURBO_TEAM
        value: "your-team-name"
      - key: TURBO_TOKEN
        sync: false
      - key: PNPM_VERSION
        value: "9.0.0"
      - key: PORT
        value: "10000"

  - type: web
    name: api
    env: node
    region: ohio
    plan: free
    rootDir: .
    buildFilter:
      paths:
        - "apps/api/**"
        - "packages/**"
        - "turbo.json"
        - "pnpm*"
    buildCommand: |
        export NODE_ENV=production
        corepack enable
        # Install all dependencies including dev dependencies
        NODE_ENV=development pnpm install --no-frozen-lockfile
        # Build API types first
        cd packages/api-types && pnpm build
        # Build API app
        cd ../../apps/api && pnpm build
    startCommand: cd apps/api && PORT=4000 pnpm start:prod
    healthCheckPath: /api/health
    port: 4000
    envVars:
      - key: NODE_ENV
        value: production
      - key: WEB_URL
        fromService:
          type: web
          name: web
          property: url
      - key: TURBO_REMOTE_ONLY
        value: "true"
      - key: TURBO_TEAM
        value: "your-team-name"
      - key: TURBO_TOKEN
        sync: false
      - key: PNPM_VERSION
        value: "9.0.0"

# Uncomment below to add Redis
# - type: redis
#   name: app-redis
#   ipAllowList: []  # Only allow internal connections
#   plan: free