version: 3
endpoint: http://localhost:8080
admin_secret: dev-admin-secret
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:4000
migrations_directory: migrations
seeds_directory: seeds
